### ISSUE TITLE
Missing date exit on OSX

### ISSUE THREAD

**Issue by mbordash** [whois-api-llc/whois_database_download_support#3]
Hi, I'm trying to run your download example (credentials removed) but the script keeps return/exiting with Missing date. Example::

`$ ./whoisdownload.sh --user=demo --password=xxxxxxx --output-dir=./tmp --date=2015-10-20 --date=2018-01-21 --tld="org info" --data-feeds="domain_names_new domain_names_dropped"
Missing date.
Use the --date=YYYY-MM-dd option to specify date.`

Please advise

**Comment by whoisxmlapi** [comment]
Hey Michael,

I wanted to give you a heads up that we got your email about the script and
we've directed it over to our Engineering team, we'll be sure to have a
response back to you shortly about this situation!

          Thanks,



*Steven Seagondollar*

*Operations Support Specialist*

*______________________________*


*WhoisXML API* - www.whoisxmlapi.com

*Direct Email* - steven@whoisxmlapi.com

*Support Email* - support@whoisxmlapi.com

*______________________________*


*Enterprise API Packages
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51LvdzJW1GGmmy3XT__3W4cgz5M4fGCnCW49M9mh1Gy7zkW1GGmmy3XT__30&si=8000000000352168&pi=86914013-fb41-4df6-9354-622bd5f7f3d7>*

*Enterprise Data Feed Packages
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51LvdzJW1GGmmy3XT__3W4cgz5M4fGCnCW49M9mh1GzmHjW3yLW9L3K2Vj4F3z8nfmW1v71&si=8000000000352168&pi=86914013-fb41-4df6-9354-622bd5f7f3d7>*

*Enterprise Security Intelligence Packages
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51LvdzJW1GGmmy3XT__3W4cgz5M4fGCnCW49M9mh1GHD7pW4hLygn4r51p_F3Z_W6yW2gZ1&si=8000000000352168&pi=86914013-fb41-4df6-9354-622bd5f7f3d7>*

_____________________________________

**Comment by whoisxmlapi** [comment]
Hello Michael,

I am sorry for the embarrassingly late reaction, and thank you very much for pointing out this issue.
The reason was that the script did use "realpath", a part of GNU coreutils not there on Mac OS X by default.
I have modified the script to avoid the use of realpath, the current version should work on Mac OS X. Alternatively the previous version will work after installing the missing dependency, e.g. like this:

 brew install coreutils && brew install gnu-getopt && brew install wget \
  && echo 'export PATH="$(brew --prefix)/opt/gnu-getopt/bin:$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"' >> ~/.zshrc \
  && source ~/.zshrc

Regards,

Matyas
